### ISSUE TITLE
Python package section request

### ISSUE THREAD

**Issue by fkromer** [tommyod/awesome-pandas#3]
There are packages related to `pandas` like e.g. [`datatest`](https://datatest.readthedocs.io/en/stable/). However there is no section for packages in the README. Shall we add one?

**Comment by tommyod** [comment]
Sure! Create a PR and I'll happily merge :+1:

**Comment by fkromer** [comment]
@tommyod https://github.com/tommyod/awesome-pandas/pull/4

**Comment by tommyod** [comment]
Thanks :+1:
